package simulateur;

public class Help {
 public Help(){
  System.out.println("Ce document récapitule les modalités d'invocation du simulateur, afin d'harmoniser l'utilisation des simulateurs rendus par les différentes équipes. La documentation ci-dessous est fournie se lon le modèle de pages man Linux.");
  System.out.println("SIMULATEUR(1)");
  System.out.println("NAME");
  System.out.println("Simulation de la transmission d'un message numérique.");
  System.out.println();
  System.out.println("SYNOPSIS");
  System.out.println("java Simulateur [...]");
  System.out.println();
  System.out.println("DESCRIPTION");
  System.out.println("Il s'agit de simuler la transmission d'un message numérique (train de bits 0 ou 1) dans un système de transmission entre un point d’entrée jusqu'à un point de sortie,via un canal de transmission (ou de communication).Les nombreux paramètres de la simulation permettent de choisir les caractéristiques du message à trans mettre, du canal de propagation et du système de transmission.");
  System.out.println("Le résultat de la simulation est la valeur du taux,d’erreur binaire de la transmission totale (TEB). Les graphiques reproduisant le signal à différents étages du système de transmission (si option –s ) sont assimilables à des résultats.");
  System.out.println();
  System.out.println(" OPTIONS :");
  System.out.println("Par défaut le simulateur doit utiliser une chaîne de transmission logique, avec un message aléatoire de longueur 100, sans utilisation de sondes et sans utilisation de transducteur.");
  System.out.println();
  System.out.println("-mess m");
  System.out.println("précise le message ou la longueur du message à émettre :");
  System.out.println("Si m est une suite de 0 et de 1 de longueur au moins égale à 7, m est le message à émettre.");
  System.out.println("Si m comporte au plus 6 chiffres décimaux et correspond à la représentation en base 10 d'un entier, cet entier est la longueur du message que le simulateur doit générer et transmettre.");
  System.out.println("Par défaut le simulateur doit générer et transmettre un message de longueur 100.");
  System.out.println();
  System.out.println("-s");
  System.out.println("indique l’utilisation des sondes. Par défaut le simulateur n’utilise pas de sondes");
  System.out.println();
  System.out.println("-seed v");
  System.out.println("précise l’utilisation d’une semence pour l’initialisation des générateurs aléatoires du simulateur. v doit être une valeur entière. L’utilisation d’une semence permet de rejouer à l’identique une simulation (à la fois pour le message émis et le bruitage s’il est activé).Par défaut le simulateur n’utilise pas de semence pour initialiser ses générateurs aléatoires.");
  System.out.println();
  System.out.println("-form f");
  System.out.println("utilisation d’une transmission analogique, f précise la forme d’onde. Le paramètre f peut prendre les valeurs suivantes :");
  System.out.println("NRZ forme d'onde rectangulaire");
  System.out.println("NRZT forme d'onde trapézoïdale (temps de montée ou de descente à 1/3 du temps bit)");
  System.out.println("RZ forme d'onde impulsionnelle (amplitudemin sur le premier et dernier tiers du temps bit, impulsionnelle sur le tiers central ave c un max au milieu du temps bit égal à l’amplitude max)");
  System.out.println("Par défaut le simulateur doit utiliser la forme d’onde RZ pour le signal analogique.");
  System.out.println();
  System.out.println("-nbEch ne");
  System.out.println("utilisation d’une transmission analogique, ne précise le nombre d’échantillons par bit. ne doit être une valeur entière positive. Par défaut le simulateur doit utiliser 30 échantillons par bit.");
  System.out.println();
  System.out.println("-ampl min max");
  System.out.println("utilisation d’une transmission analogique, min et max précisent l’amplitude min et max du signal. min et max doivent être des valeurs flottantes (avec min < max ). Par défaut, le simulateur doit utiliser 0.0f comme min et 1.0f comme max.");
  System.out.println();
  System.out.println("-snr s");
  System.out.println("utilisation d’une transmission analogique bruitée, c'est la valeur du rapport signal sur bruit (SNR en dB). Le paramètre s doit être une valeur flottante.");
  System.out.println();
  System.out.println("-ti i dt ar");
  System.out.println("utilisation d’une transmission analogique multitrajet. dt précise le décalage temporel (en nombre d’échantillons) entre le i ème trajet indirect du signal et le trajet direct, ar précise l’amplitude relative du signal du i ème trajet indirect par rapport à celle du signal du trajet direct. Les paramètres i, dt et ar doivent être respectivement une valeur entière (de 1 à 5), une valeur entière et une valeur flottante. Par défaut le simulateur doit utiliser 0 et 0. 0f pour tous les trajets indirects (5 au maximum).");
  System.out.println();
  System.out.println("-transducteur");
  System.out.println("précise l’utilisation d’un transducteur (en émission et réception). Par défaut, le simulateur n’utilise pas de transducteur.");
  System.out.println();
  System.out.println("-aveugle");
  System.out.println("précise l’utilisation de mécanismes de détermination, dans les étages de réception du signal analogique, des amplitudes min et max, des retards et de leurs amplitudes relatives. Par défaut, le simulateur n’utilise pas ces mécanismes, et les valeurs des amplitudes min et max, de s retards et de leurs amplitudes relatives sont des paramètres des étages de réception. ");
  System.out.println();
  System.out.println("-h -help");
  System.out.println("premet d'afficher ce messge d'aide");
  System.out.println();
  System.out.println("-test");
  System.out.println("Permets de générer un fichier .Csv qui contient les échantillons du bruit génég�s par le simulateur ne fonctionne que lorsque la transmission est bruitée");
 }
}
